package:
  name: tike
  version: alpha

source:
  path: .

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed
      --no-cache-dir --no-binary :all: -vvv"

requirements:
  host:
    - pip
    - python={{ python }}
    - setuptools_scm_git_archive
  run:
    - cupy>=7
    - importlib_resources
    - matplotlib-base
    - numpy>=1.17
    - python={{ python }}
    - py-opencv
    - scipy
    - setuptools

test:
  requires:
    - pytest
  imports:
    - tike
    - tike.operators
    - tike.opt
    - tike.ptycho
    - tike.scan
    - tike.trajectory
    - tike.view

  source_files:
    - tests/*
  commands:
    - pytest tests/

app:
    own_environment: True

about:
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
