# tomopy makefile for Windows

include Mk.config

CC_WARNINGS  = -Wall
CC_OPTIMIZE  = -mdll -O -DMS_WIN64 -DUSE_MKL
CC           = $(COMPILER_DIR) $(CC_OPTIMIZE) $(CC_WARNINGS) $(INCLUDE) \
               -DPY3K -DWIN32 -std=c11
LINK_LIBWIN  = $(LINK_LIB)/Library $(LINK_LIB)/Library/bin $(LINK_LIB)/libs \
               $(LINK_LIB)/PCBuild/amd64
LINK         = $(COMPILER_DIR) -shared -s $(LINK_LIBWIN) -lvcruntime140

include Mk.base
