name: CI

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: "Lint with pycodestyle"
        uses: rahul-deepsource/pyaction@1.4.1
        with:
          python-root-list: "src/ tests/"
          use-pycodestyle: true
          use-mypy: false
          use-vulture: false
          use-flake8: false
          use-pylint: false
          use-isort: false
          use-black: false
